# Generated by Django 2.1 on 2023-02-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.CharField(default='01127210144', max_length=50, verbose_name='Mobile number'),
        ),
    ]
